### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'find_links'

### ISSUE THREAD

**Issue by miku** [frostming/pipfile-requirements#3]
Thanks for your project. Installation worked without problems, however on first run I got an error (see below).

* Python 3.7.4
* pip 19.3.1
* Ubuntu 18.04.3 LTS x86_64

```
$ pipfile2req
Traceback (most recent call last):
  File "/home/zzz/.virtualenvs/fatcat/bin/pipfile2req", line 8, in <module>
    sys.exit(main())
  File "/home/zzz/.virtualenvs/fatcat/lib/python3.7/site-packages/pipfile_requirements.py", line 102, in main
    lines = convert_pipfile_or_lock(args.project, args.file, args.hashes, args.dev)
  File "/home/zzz/.virtualenvs/fatcat/lib/python3.7/site-packages/pipfile_requirements.py", line 97, in convert_pipfile_or_lock
    return _convert_pipfile_lock(full_path, hashes, dev)
  File "/home/zzz/.virtualenvs/fatcat/lib/python3.7/site-packages/pipfile_requirements.py", line 63, in _convert_pipfile_lock
    return lockfile.as_requirements(hashes, dev=dev)
  File "/home/zzz/.virtualenvs/fatcat/lib/python3.7/site-packages/requirementslib/models/lockfile.py", line 301, in as_requirements
    section = self.dev_requirements if dev else self.requirements
  File "/home/zzz/.virtualenvs/fatcat/lib/python3.7/site-packages/requirementslib/models/lockfile.py", line 283, in requirements
    self._requirements = list(self.get_requirements(dev=False, only=True))
  File "/home/zzz/.virtualenvs/fatcat/lib/python3.7/site-packages/requirementslib/models/lockfile.py", line 272, in get_requirements
    yield Requirement.from_pipfile(k, v)
  File "/home/zzz/.virtualenvs/fatcat/lib/python3.7/site-packages/requirementslib/models/requirements.py", line 2841, in from_pipfile
    r = FileRequirement.from_pipfile(name, pipfile)
  File "/home/zzz/.virtualenvs/fatcat/lib/python3.7/site-packages/requirementslib/models/requirements.py", line 1945, in from_pipfile
    arg_dict["setup_info"] = arg_dict["parsed_line"].setup_info
  File "/home/zzz/.virtualenvs/fatcat/lib/python3.7/site-packages/requirementslib/models/requirements.py", line 809, in setup_info
    self.setup_info = self.get_setup_info()
  File "/home/zzz/.virtualenvs/fatcat/lib/python3.7/site-packages/requirementslib/models/requirements.py", line 794, in get_setup_info
    setup_info = SetupInfo.from_ireq(self.ireq)
  File "/home/zzz/.virtualenvs/fatcat/lib/python3.7/site-packages/requirementslib/models/setup_info.py", line 1446, in from_ireq
    finder = get_finder()
  File "/home/zzz/.virtualenvs/fatcat/lib/python3.7/site-packages/requirementslib/models/dependencies.py", line 634, in get_finder
    session=session,
TypeError: __init__() got an unexpected keyword argument 'find_links'

```

**Comment by miku** [comment]
Just as a footnote: I was able to convert a Pipfile.lock to requirements.txt-ish list via [jq](https://stedolan.github.io/jq/), e.g.:

```
$ pip install -r <(jq -r '.default, .develop | keys[]' Pipfile.lock)
```

**Comment by kamzil** [comment]
This is still a problem for me and is not resolved. Having a this under [dev-packages] causes it:
`my-library-name = {editable = true,path = "."}`
